@startmindmap
top to bottom direction

* Result
** 2023
*** price
**** FR
**** DE
**** CN
*** count
**** FR
**** DE
**** CN
** 2024
*** price
**** FR
**** DE
**** CN
*** count
**** FR
**** DE
**** CN
@endmindmap