@startmindmap
top to bottom direction

* Result
** 2023
*** FR
**** price
**** count
*** DE
**** price
**** count
*** CN
**** price
**** count
** 2024
*** FR
**** price
**** count
*** DE
**** price
**** count
*** CN
**** price
**** count
@endmindmap