@startuml mapper

class Mapper
Mapper ..> MainTransformer

class MainTransformer
MainTransformer ..> ObjectCacheFactory
MainTransformer ..> TransformerRegistry
' MainTransformer ..> TypeResolver


TransformerRegistry ..> Transformer
' TransformerRegistry ..> TypeResolver
TransformerRegistry ..> MappingFactory

interface Transformer

interface Transformer&MainTransformerAware
Transformer <|.. "Transformer&MainTransformerAware"
"Transformer&MainTransformerAware" ..> MainTransformer

class ArrayToObjectTransformer
ArrayToObjectTransformer ..> SymfonySerializer
Transformer <|.. ArrayToObjectTransformer

class ObjectToArrayTransformer
ObjectToArrayTransformer ..> SymfonySerializer
Transformer <|... ObjectToArrayTransformer

class ClassMethodTransformer
ClassMethodTransformer ..> SubMapperFactory
Transformer <|..... ClassMethodTransformer

class ObjectMapperTransformer implements Transformer
"Transformer&MainTransformerAware" <|.. ObjectMapperTransformer
ObjectMapperTransformer .....> SubMapperFactory
ObjectMapperTransformer ....> ObjectMapperTableFactory  
ObjectMapperTransformer ..> ObjectMapperResolver
ObjectMapperTransformer ..> ObjectMapper

ObjectMapperResolver ..> ObjectMapper

class ObjectToObjectTransformer
"Transformer&MainTransformerAware" <|..... ObjectToObjectTransformer
ObjectToObjectTransformer ..> ProxyRegistry
ObjectToObjectTransformer ..> ObjectToObjectMetadataFactory
ObjectToObjectTransformer ......> PropertyMapper
ObjectToObjectTransformer ...> SubMapperFactory

ObjectToObjectMetadataFactory ...> EagerPropertiesResolver
ObjectToObjectMetadataFactory ...> SymfonyPropertyInfo
ObjectToObjectMetadataFactory ...> PropertyMapperResolver
ObjectToObjectMetadataFactory ..> ProxyGenerator
' ObjectToObjectMetadataFactory ..> TypeResolver

class TraversableToArrayAccessTransformer
"Transformer&MainTransformerAware" <|.. TraversableToArrayAccessTransformer
TraversableToArrayAccessTransformer ..> ArrayLikeMetadataFactory

class TraversableToTraversableTransformer
"Transformer&MainTransformerAware" <|... TraversableToTraversableTransformer
TraversableToTraversableTransformer ..> ArrayLikeMetadataFactory

PropertyMapperResolver ..> PropertyMapper

' ObjectCacheFactory ..> TypeResolver

' MappingFactory ..> TypeResolver
MappingFactory ..> Transformer

ObjectMapperResolver ..> ObjectMapperTableFactory

SubMapperFactory ...> SymfonyPropertyInfo
SubMapperFactory ..> PropertyAccessor


@enduml